---

- hosts: all
  become: true
  tasks:
  
  # updating package index
  - name: update repository index
    apt:
      update_cache: yes

  # Install apache2 package
  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest