---

- hosts: all
  become: true
  tasks:
  
 
  # Install apache package
  - name: install apache2 package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
