---
# These plays are ran in all servers
- hosts: all
  become: true
  pre_tasks:

  - name: install update (centos)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: install update (ubuntu)
    tags: always
    apt:
      # upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# Below plays will be ran in the servers which are in the web server group
- hosts: web_servers
  become: true
  tasks: 
 
  # Install apache2 package
  - name: install apache2 package
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  # Centos
  # Install httpd package
  - name: install httpd package
    tags: apache,apache2,centos
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  # copy files bydefault it searches under the files directory
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install maridb
    tags: database,ubuntu
    apt:
      name: mariadb-server
      state: latest

    when: ansible_distribution == "Ubuntu"

#  installing the terraform in the local workstation setup
- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: unzip the terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root