---
# These plays are ran in all servers
- hosts: all
  become: true
  pre_tasks:

  - name: run index update (centos)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false # it keeps the changed value in the output 0 will not considered this task status in the output
    when: ansible_distribution == "CentOS"


  - name: run index update (ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

# below play is there to create user in the server 
- hosts: all
  become: true
  roles:
    - base
    
# Below plays will be ran in the servers which are in the web server group
- hosts: web_servers
  become: true
  roles:
    - web_servers


- hosts: db_servers
  become: true
  roles:
    - db_servers

#  installing the terraform in the local workstation setup
- hosts: workstations
  become: true
  roles:
    - workstations