- name: add ssh authorized key
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILka1m9fw9qKroEDSEtjwXuLxfzlbxdVwXWmXL3x+meT ansible"

- name: allow users in ssh configuration
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh